#服务相关设置
server:
    port: 2551

#Spring相关设置
spring:
    #应用相关配置
    application:
        name: ${project.name}
    #Servlet相关配置
    servlet:
        multipart:
            max-file-size: 100MB
            max-request-size: 1000MB

datasource:
    mysql:
        jdbc-url: jdbc:mariadb://118.24.3.84:3306/mysql?useUnicode=true&characterEncoding=utf-8
        username: zhangbin
        password: zhangbin